global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files: [prometheus-rules.yml]

scrape_configs:
  - job_name: api
    static_configs: [{ targets: ["api:8000"] }]
  - job_name: agent
    static_configs: [{ targets: ["agent:8001"] }]
  - job_name: detect
    static_configs: [{ targets: ["detect:8002"] }]
  - job_name: detect-worker
    static_configs: [{ targets: ["detect-worker:8012"] }]
  - job_name: ingest
    static_configs: [{ targets: ["ingest:8010"] }]
  - job_name: mock-mes
    static_configs: [{ targets: ["mock-mes:8003"] }]
  - job_name: redpanda
    metrics_path: /public_metrics
    static_configs: [{ targets: ["redpanda:9644"] }]
