apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  backoffLimit: 20
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-postgres
        image: postgres:16.4@sha256:e62fbf9d3e2b49816a32c400ed2dba83e3b361e6833e624024309c35d334b412
        command:
        - sh
        - -c
        - until pg_isready -h postgres -U qgate_migrate -d qgate; do sleep 3; done
      - name: migrate
        image: amacneil/dbmate:2.19@sha256:84043c7409dec5494d861c3c1779adbe28a41a283cf8103e6c08f7b829f5563d
        args:
        - up
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qgate-secrets
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: postgres://qgate_migrate:$(POSTGRES_PASSWORD)@postgres:5432/qgate?sslmode=disable
        - name: DBMATE_MIGRATIONS_DIR
          value: /db/migrations
        - name: DBMATE_NO_DUMP_SCHEMA
          value: 'true'
        volumeMounts:
        - name: migrations
          mountPath: /db/migrations
          readOnly: true
      - name: roles
        image: postgres:16.4@sha256:e62fbf9d3e2b49816a32c400ed2dba83e3b361e6833e624024309c35d334b412
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qgate-secrets
              key: POSTGRES_PASSWORD
        - name: PGPASSWORD
          value: $(POSTGRES_PASSWORD)
        command:
        - sh
        - -c
        - psql -h postgres -U qgate_migrate -d qgate -v ON_ERROR_STOP=1 -v pw="$POSTGRES_PASSWORD" -f
          /db/set_role_passwords.sql
        volumeMounts:
        - name: roles
          mountPath: /db
          readOnly: true
      containers:
      - name: seed-dims
        image: ghcr.io/zakaria17amir/qgate-gen:0.1.0-rc1
        args:
        - seed-dims
        - --scenarios-dir
        - /workspace/scenarios
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: qgate-secrets
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: postgres://ingest_rw:$(POSTGRES_PASSWORD)@postgres:5432/qgate
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
      volumes:
      - name: migrations
        configMap:
          name: qgate-migrations
      - name: roles
        configMap:
          name: qgate-roles-sql
