apiVersion: v1
kind: Service
metadata:
  name: redpanda
spec:
  clusterIP: None
  selector:
    app: redpanda
  ports:
  - port: 9092
    name: kafka
  - port: 8081
    name: registry
  - port: 9644
    name: admin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: redpanda
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
      - name: redpanda
        image: redpandadata/redpanda:v24.2.7@sha256:82a69763bef8d8b55ea5a520fa1b38f993908ef68946819ca1aed43541824c48
        args:
        - redpanda
        - start
        - --smp
        - '1'
        - --memory
        - 1G
        - --overprovisioned
        - --kafka-addr
        - internal://0.0.0.0:9092
        - --advertise-kafka-addr
        - internal://redpanda:9092
        - --schema-registry-addr
        - 0.0.0.0:8081
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 8081
          name: registry
        - containerPort: 9644
          name: admin
        readinessProbe:
          httpGet:
            path: /v1/status/ready
            port: admin
          periodSeconds: 5
          initialDelaySeconds: 10
        volumeMounts:
        - name: data
          mountPath: /var/lib/redpanda/data
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            memory: 2Gi
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
